const ar = {
    'occasions':'مناسبات',
    'skip':'تخطي',
    'concerts':'حفلات',
    'matches':'مباريات',
    'phoneNumber': 'رقم الجوال',
    'password': 'كلمة المرور',
    'forgetPass': 'نسيت كلمة المرور ؟',
    'visitor': 'الدخول كزائر',
    'loginButton': 'دخول',
    'registerButton': 'تسجيل',
    'sendButton': 'ارسال',
    'verifyCode': 'كود التحقق',
    'newPass': 'كلمة المرور الجديدة',
    'verifyNewPass': 'تأكيد كلمة المرور الجديدة',
    'confirm': 'تأكيد',
    'username': 'اسم المستخدم',
    'email': 'البريد الالكتروني',
    'noNotifications': 'لا يوجد اشعارات',
    'language': 'اللغة',
    'stopNotification': 'غلق الاشعارات',
    'shareApp': 'مشاركة التطبيق',
    'home': 'الرئيسية',
    'aboutApp': 'عن التطبيق',
    'terms' : 'احكام وشروط',
    'contactUs' : 'اتصل بنا',
    'settings' : 'الاعدادات',
    'logout' : 'تسجيل الخروج',
    'notifications' : 'الاشعارات',
    'notificationDeleted' : 'تم حذف الاشعار',
    'search' : 'بحث',
    'proposedEvents' : 'الايفينتات المقترحة',
    'commonEvents' : 'الايفينتات الشائعة',
    'favoriteEvents' : 'الايفينتات المفضلة',
    'RS' : 'ر.س',
    'city' : 'المدينة',
    'date' : 'التاريخ',
    'time' : 'الوقت',
    'cancel' : 'الغاء',
    'paymentConfirmed' : 'تم تأكيد الدفع',
    'ticket' : 'التذكرة',
    'confirmQr' : 'تم تأكيد الكود QR يستخدم لمرة واحدة فقط للايفينت الخاص به',
    'address' : 'العنوان',
    'complaint' : 'ارسال شكوي او استفسار',
    'msg' : 'نص الرسالة',
    'reservation' : 'حجز',
    'paymentMethod' : 'اختر وسيلة الدفع',
    'payOnline' : 'دفع اونلاين',
    'remaining' : 'متبقي',
    'process' : 'قم بعملية مسح لكود QR',
    'deleteTicket' : 'حذف التذكرة',
    'changePass' : 'تغيير كلمة المرور',
    'chooseLang' : 'اختر لغة التطبيق',
}

export default ar;